Add files via upload
BSUIR-OOP/laboratory-work-1-dungeon-slave pull request #2
Opened 2022-03-15 12:19 UTC by dungeon-slave

2022-03-17 10:46 UTC, WildTiger404 commented
the branch name should provide the information about what it will develop or some key names like dev, main etc for the release or deployment

2022-03-17 11:21 UTC, WildTiger404 requested changes

2022-03-17 11:21 UTC, WildTiger404 commented on Circle.cs
> +        return (coordX * coordX) + (coordY * coordY) <= 0.5; //(coordX * coordX) + (coordY * coordY) <= R^2
finally some good comment attempt.
It's okay, but if you replace //(coordX * coordX) + (coordY * coordY) with some words it would be perfect

2022-03-17 11:21 UTC, WildTiger404 commented on FigureList.cs
> +    private Dot[] FiguresArray = new Dot[6];
Well, I close my eyes to magic numbers. You know by yourself, that's not a good collection at all

2022-03-17 11:21 UTC, WildTiger404 commented on FigureList.cs
> +    private Dot[] FiguresArray = new Dot[6];
What if I need to delete items? Or have more than 6 items?

2022-03-17 11:21 UTC, WildTiger404 commented on FigureList.cs
> +    private Dot[] FiguresArray = new Dot[6];
If you want. You can try to implement collection that would work with foreach, but for now you can just use List\<Dot> instead of your own collection

2022-03-17 11:25 UTC, WildTiger404 commented
Also you should add some folder hierarchy, like models, renderers etc.

2022-03-17 11:29 UTC, WildTiger404 commented on Dot.cs
> +        return (coordX == coordX0) && (coordY == coordY0); //(coordX == X0) && (coordY == Y0)
If you write this comment you think, that people who would read your code can have some questions to this line. Do you think you can have more readable variable names in that case?

2022-03-24 20:09 UTC, dungeon-slave commented on Circle.cs
> +        return (coordX * coordX) + (coordY * coordY) <= 0.5; //(coordX * coordX) + (coordY * coordY) <= R^2
А что с этими именами не так?

2022-03-25 08:24 UTC, dungeon-slave reviewed
Исправил FigureList.cs и Program.cs

2022-03-25 08:27 UTC, closed without merging